// Auto-generated by Launchpad — site access gate. Do not edit manually.
const GATE_USER = "lp";
const GATE_KEY = "7-88MnuWeduzkj9jvpAzDc0h";
const GATE_REALM = "few";
function checkAuth(request: Request): boolean {
  const header = request.headers.get("Authorization") ?? "";
  if (!header.startsWith("Basic ")) return false;
  let decoded = "";
  try {
    decoded = atob(header.slice(6));
  } catch {
    return false;
  }
  const sep = decoded.indexOf(":");
  if (sep === -1) return false;
  const user = decoded.slice(0, sep);
  const pass = decoded.slice(sep + 1);
  if (user !== GATE_USER || pass.length !== GATE_KEY.length) return false;
  let diff = 0;
  for (let i = 0; i < pass.length; i++) diff |= pass.charCodeAt(i) ^ GATE_KEY.charCodeAt(i);
  return diff === 0;
}
function unauthorized() {
  return new Response("Unauthorized", {
    status: 401,
    headers: { "WWW-Authenticate": `Basic realm="${GATE_REALM}"` },
  });
}
type GateApp = {
  fetch(request: Request, env?: unknown, ctx?: unknown): Promise<Response> | Response;
};
const appPromise = import("./index");
export default {
  async fetch(request: Request, env?: unknown, ctx?: unknown): Promise<Response> {
    if (!checkAuth(request)) return unauthorized();
    const app = (await appPromise).default as unknown as GateApp;
    return app.fetch(request, env, ctx);
  },
};
